### ISSUE TITLE
Using React.lazy breaks a [contenthash] in production

### ISSUE THREAD

**Issue by PieterBoeren** [single-spa/single-spa-css#11] opened 2021-08-24 13:16 UTC
When I use a React.lazy to split my code, loading a css file with a [contenthash] doesn't work anymore in production (it does work in development). In my case it tries to load "main.undefined.css:

![image](https://user-images.githubusercontent.com/43775697/130615882-6b185b6f-e634-4461-a364-bb2f6b9f08c1.png)

While debugging I get to this point:

![image](https://user-images.githubusercontent.com/43775697/130616018-41f6ea3a-ef45-44c5-9c17-a9886c6dac23.png)

"t" is always "main" and never 179, thus it will never resolve the css file.

Reproduction repostitory: https://github.com/PieterBoeren/single-spa-css-react-lazy-issue. In the "root.component.tsx" there is a React.lazy (not even used!), but if you comment that one out, everything is working as expected. Also note the start script, that contains a "mode=production".

**Comment by matthewlee-toast** [comment] 2021-08-30 19:45
+1 

I've run into the the same with the basically the same setup as the reproduction repository.

**Comment by tjfred35** [comment] 2021-09-03 02:04
I can fix this like this, but why is it a single array? Does ExposedCssRuntimeModule only support one css asset at this time? 

```
class ExposedCssRuntimeModule extends RuntimeModule {
  constructor() {
    super("exposed-css-runtime", 10);
  }
  generate() {
    return Template.asString(
      `${RuntimeGlobals.require}.cssAssets = ${JSON.stringify(
        [this.chunk.id] // Wait until generate and pull the chunk's id, not the chunk's name -
      )};`
    );
  }
}
```

**Comment by tjfred35** [comment] 2021-09-03 17:52
I think that cssAssets, although documented here https://single-spa.js.org/docs/ecosystem-css/ as containing the name of the webpack chunk, ought to contain the id of the webpack chunk, since cssAssetFileNames is generated by GetChunkFilenameRuntimeModule, which is a function whose only parameter is called, `chunkId`. If that is breaking anyone's expectations or usages, then perhaps we need to create a `cssAssetIds` array and export cssAssets only for whatever unknown usages people are putting it to?

**Comment by joeldenning** [comment] 2021-09-09 19:02
One thing to note is that React.lazy() doesn't impact anything with webpack, css assets, or single-spa-css, but dynamic import does (`import()`).

We support loading multiple css files/chunks with ExposeRuntimeCssAssetsPlugin, including those lazy loaded with `import()`. I reviewed #14 and think it'll be merged and published after a round or two of feedback.

**Closed** 2021-10-18 22:45 UTC

**Comment by priyassg** [comment] 2024-04-29 19:22
I recently encountered this issue in Production. Works fine in Dev env.
Using "single-spa-css": "^1.1.2"
Is this issue still unresolved?
